"use client";

import { ReactNode, useEffect, useMemo, useState } from "react";
import { CalendarDays, Camera, Check, ChevronRight, Clock3, Download, FileText, FolderOpen, Home, Loader2, Menu, MoreHorizontal, Pause, Play, Plus, RefreshCw, Search, Settings, Trash2, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { UserButton } from "@clerk/nextjs";

type Project={id:string;name:string;address:string;status:string;color:string;due_date:string|null;progress:number};
type EventRow={id:string;project_id:string;project_name:string;address:string;color:string;title:string;starts_at:string;ends_at:string;assigned_members:{id:string;display_name:string}[]};
type NoteRow={id:string;body:string;done:number|boolean;author_name:string;created_at:string};
type FileRow={id:string;name:string;content_type:string;size:number;kind:"photo"|"document";uploaded_by_name:string;created_at:string};
type Member={id:string;display_name:string;email:string|null;role:string;status:string};
type CompanyMember=Member&{user_id:string|null;has_avatar:number|boolean;avatar_version:string|null};
type ProjectMember=Member&{project_id:string};
type Activity={id:string;actor_name:string;action:string;detail:string;created_at:string};
type Dashboard={user:{userId:string;displayName:string;email:string};projects:Project[];selectedProjectId?:string;events:EventRow[];notes:NoteRow[];files:FileRow[];members:Member[];allMembers:ProjectMember[];companyMembers:CompanyMember[];activities:Activity[];timer:{id:string;project_id:string;starts_at:string}|null;canAdminProject:boolean;canAdminCompany:boolean};

const days=["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"];
const fmtTime=(iso:string)=>new Date(iso).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});
const fmtDate=(iso:string)=>new Date(iso).toLocaleDateString("fr-FR",{day:"numeric",month:"short"});
const initials=(name:string)=>name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
const imageExtensions=["heic","heif","jpg","jpeg","png","webp"];
const isImageFile=(file:File)=>file.type.startsWith("image/")||imageExtensions.includes(file.name.split(".").pop()?.toLowerCase()||"");

async function prepareUploadFile(file:File){
  if(!isImageFile(file)||file.size<=700*1024)return file;
  const url=URL.createObjectURL(file);
  try{
    const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Cette photo ne peut pas être préparée."));img.src=url});
    let width=image.naturalWidth,height=image.naturalHeight;
    const maxSide=1600;
    if(Math.max(width,height)>maxSide){const ratio=maxSide/Math.max(width,height);width=Math.round(width*ratio);height=Math.round(height*ratio)}
    const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;
    const context=canvas.getContext("2d");if(!context)throw new Error("Cette photo ne peut pas être préparée.");
    context.fillStyle="#fff";context.fillRect(0,0,width,height);context.drawImage(image,0,0,width,height);
    let result:Blob|null=null;
    for(const quality of [0.82,0.7,0.58]){
      result=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",quality));
      if(result&&result.size<=700*1024)break;
    }
    if(!result)throw new Error("Cette photo ne peut pas être préparée.");
    const name=file.name.replace(/\.[^.]+$/,"")||"photo";
    return new File([result],`${name}.jpg`,{type:"image/jpeg",lastModified:Date.now()});
  }finally{URL.revokeObjectURL(url)}
}

export default function HomePage(){
  const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [tab,setTab]=useState("apercu"),[section,setSection]=useState("accueil"),[query,setQuery]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);
  const [projectOpen,setProjectOpen]=useState(false),[eventOpen,setEventOpen]=useState(false),[inviteOpen,setInviteOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[manageEvent,setManageEvent]=useState<EventRow|null>(null);
  async function load(project?:string){setLoading(true);setError("");try{const r=await fetch("/api/dashboard"+(project?`?project=${encodeURIComponent(project)}`:""),{cache:"no-store",credentials:"same-origin"});if(!r.ok){const message=await r.text();throw new Error(message||`Erreur ${r.status}`)}setData(await r.json())}catch(e){setError(e instanceof Error?`Impossible de charger les données (${e.message}).`:"Impossible de charger les données. Réessayez.")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!data?.timer)return;const id=setInterval(()=>setTick(x=>x+1),1000);return()=>clearInterval(id)},[data?.timer]);
  async function action(payload:Record<string,unknown>,success?:string){setBusy(true);try{const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json() as {error?:string;id?:string};if(!r.ok)throw new Error(body.error);if(success)toast.success(success);await load(body.id&&payload.action==="createProject"?body.id:data?.selectedProjectId);return true}catch(e){toast.error(e instanceof Error?e.message:"Enregistrement impossible");return false}finally{setBusy(false)}}
  const project=data?.projects.find(p=>p.id===data.selectedProjectId);
  const filteredFiles=useMemo(()=>data?.files.filter(f=>f.name.toLowerCase().includes(query.toLowerCase()))??[],[data?.files,query]);
  const elapsed=data?.timer?Math.max(0,Math.floor((Date.now()-Date.parse(data.timer.starts_at))/1000)):0; void tick;
  const timeText=[Math.floor(elapsed/3600),Math.floor(elapsed%3600/60),elapsed%60].map(n=>String(n).padStart(2,"0")).join(":");

  if(loading&&!data)return <State icon={<Loader2 className="animate-spin"/>} title="Chargement des chantiers…"/>;
  if(error&&!data)return <State icon={<RefreshCw/>} title={error} action={()=>load()}/>;
  if(!data)return null;

  return <div className="min-h-screen bg-[#f3f5f7] text-[#18202b]"><Toaster position="top-right"/>
    <header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b bg-white px-4 md:px-7">
      <div className="flex items-center gap-3"><button className="md:hidden" aria-label="Menu"><Menu/></button><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#165b54] font-black text-white">S</div><div><div className="font-extrabold leading-4">Suivi Chantier</div><div className="text-xs text-slate-500">Atelier & pose</div></div></div>
      <div className="hidden w-[360px] items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 md:flex"><Search size={17}/><input className="w-full bg-transparent text-sm outline-none" placeholder="Rechercher un chantier, un document…"/></div>
      <div className="flex items-center gap-3"><div className="hidden text-right sm:block"><div className="max-w-48 truncate text-sm font-bold">{data.user.displayName}</div><div className="text-xs text-slate-500">{data.canAdminProject?"Administrateur":"Membre"}</div></div><UserButton appearance={{elements:{avatarBox:"h-9 w-9"}}}/></div>
    </header>
    <div className="mx-auto flex max-w-[1500px]">
      <aside className="sticky top-16 hidden h-[calc(100vh-64px)] w-60 shrink-0 border-r bg-white p-4 md:block">
        <Nav icon={<Home/>} label="Vue d’ensemble" active={section==="accueil"} onClick={()=>setSection("accueil")}/><Nav icon={<CalendarDays/>} label="Agenda" active={section==="agenda"} onClick={()=>setSection("agenda")}/><Nav icon={<FolderOpen/>} label="Chantiers" badge={String(data.projects.length)} active={section==="chantiers"} onClick={()=>setSection("chantiers")}/><Nav icon={<Clock3/>} label="Temps" active={section==="temps"} onClick={()=>setSection("temps")}/><Nav icon={<Users/>} label="Équipe" active={section==="equipe"} onClick={()=>setSection("equipe")}/>
        <div className="mt-6 border-t pt-5"><div className="mb-2 px-3 text-xs font-bold uppercase tracking-wider text-slate-400">Chantiers actifs</div>{data.projects.map(p=><button key={p.id} onClick={()=>load(p.id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm font-semibold ${p.id===data.selectedProjectId?"bg-slate-100":"hover:bg-slate-50"}`}><span className="h-2.5 w-2.5 rounded-full" style={{background:p.color}}/>{p.name}</button>)}</div>
        <div className="absolute bottom-5 left-4 right-4"><Nav icon={<Settings/>} label="Réglages" onClick={()=>toast("Les réglages seront disponibles ici.")}/></div>
      </aside>
      <main className="min-w-0 flex-1 p-4 pb-24 md:p-7">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-semibold text-[#29756d]">{new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})}</div><h1 className="text-2xl font-black tracking-tight md:text-3xl">{section==="accueil"?`Bonjour ${data.user.displayName.split(" ")[0]} 👋`:section[0].toUpperCase()+section.slice(1)}</h1><p className="mt-1 text-slate-500">{section==="accueil"?"Voici ce qui est prévu aujourd’hui.":"Toutes les informations de votre équipe, au même endroit."}</p></div><NewProject open={projectOpen} setOpen={setProjectOpen} busy={busy} onSubmit={async p=>{if(await action({action:"createProject",...p},"Chantier créé"))setProjectOpen(false)}}/></div>

        {section==="chantiers"?<ProjectGrid projects={data.projects} onSelect={id=>{load(id);setSection("accueil")}}/>:
        section==="equipe"?<TeamView members={data.companyMembers} currentEmail={data.user.email} canAdmin={data.canAdminCompany} busy={busy} onInvite={()=>setInviteOpen(true)} onRoleChange={(memberId,role)=>action({action:"setCompanyMemberRole",projectId:data.selectedProjectId,memberId,role},"Autorisations modifiées")} onDelete={memberId=>action({action:"deleteCompanyMember",projectId:data.selectedProjectId,memberId},"Membre supprimé")} onPhoto={async(memberId,file)=>{setBusy(true);try{const preparedFile=await prepareUploadFile(file);const form=new FormData();form.append("memberId",memberId);form.append("file",preparedFile,preparedFile.name);const response=await fetch("/api/team-photo",{method:"POST",body:form});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Enregistrement impossible");toast.success("Photo du membre enregistrée");await load(data.selectedProjectId)}catch(e){toast.error(e instanceof Error?e.message:"Enregistrement impossible")}finally{setBusy(false)}}}/>:
        section==="agenda"?<AgendaView events={data.events} onAdd={()=>setEventOpen(true)} onManage={setManageEvent}/>:
        section==="temps"?<TimeView timer={data.timer} timeText={timeText} onToggle={()=>action({action:"timer",projectId:data.selectedProjectId},"Pointage mis à jour")}/>:
        <>
          <section className="mb-6 grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
            <div className="rounded-2xl border bg-white p-4 shadow-sm md:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-extrabold">Agenda de la semaine</h2><p className="text-sm text-slate-500">{data.events.length} intervention{data.events.length>1?"s":""}</p></div><Button variant="outline" size="sm" onClick={()=>setSection("agenda")}>Voir l’agenda <ChevronRight/></Button></div><WeekStrip/><div className="space-y-3">{data.events.slice(0,3).map(e=><EventItem key={e.id} e={e} onManage={()=>setManageEvent(e)}/>)}</div></div>
            <div className="space-y-4"><div className="overflow-hidden rounded-2xl bg-[#123f3b] p-5 text-white shadow-sm"><div className="flex items-start justify-between"><div><div className="text-sm text-emerald-100">{data.timer?"Pointage en cours":"Temps aujourd’hui"}</div><div className="mt-2 text-4xl font-black">{data.timer?timeText:"00:00:00"}</div></div><Clock3 className="text-emerald-200"/></div><div className="mt-4 text-sm text-emerald-50">{project?.name??"Choisir un chantier"}</div><Button disabled={busy||!project} onClick={()=>action({action:"timer",projectId:project?.id},"Pointage mis à jour")} className="mt-5 w-full rounded-xl bg-white text-[#123f3b] hover:bg-emerald-50">{data.timer?<><Pause/>Arrêter le chrono</>:<><Play/>Démarrer le chrono</>}</Button></div>
              <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-extrabold">Équipe du chantier</h2>{data.canAdminProject&&<button onClick={()=>setInviteOpen(true)} className="text-sm font-bold text-[#29756d]">Inviter</button>}</div>{data.members.map(m=><Person key={m.id} m={m}/>)}</div>
            </div>
          </section>
          {project&&<ProjectDetail project={project} tab={tab} setTab={setTab} data={data} query={query} setQuery={setQuery} note={note} setNote={setNote} busy={busy} filteredFiles={filteredFiles} onDelete={()=>setDeleteOpen(true)}
            addNote={async()=>{if(note.trim()&&await action({action:"addNote",projectId:project.id,body:note},"Modification ajoutée"))setNote("")}}
            toggleNote={id=>action({action:"toggleNote",projectId:project.id,id})}
            upload={async file=>{setBusy(true);try{const preparedFile=await prepareUploadFile(file);const form=new FormData();form.append("projectId",project.id);form.append("file",preparedFile,preparedFile.name);const r=await fetch(new URL("/api/upload",window.location.origin),{method:"POST",body:form,credentials:"same-origin"});const text=await r.text();let body:{error?:string;id?:string}={};try{body=text?JSON.parse(text):{}}catch{body={error:text||`Erreur ${r.status}`}}if(!r.ok)throw new Error(body.error||`Erreur ${r.status}`);toast.success(isImageFile(preparedFile)?"Photo enregistrée":"Document enregistré");await load(project.id)}catch(e){toast.error(e instanceof Error?e.message:"Téléchargement impossible")}finally{setBusy(false)}}}/>} 
        </>}
      </main>
    </div>
    <nav className="fixed bottom-0 left-0 right-0 z-40 grid grid-cols-5 border-t bg-white px-2 py-2 md:hidden">{[["accueil",<Home/>],["agenda",<CalendarDays/>],["chantiers",<FolderOpen/>],["temps",<Clock3/>],["equipe",<Users/>]].map(([s,i])=><button key={s as string} onClick={()=>setSection(s as string)} className={`flex flex-col items-center gap-1 text-[10px] font-bold ${section===s?"text-[#165b54]":"text-slate-500"}`}><span className="[&>svg]:h-5 [&>svg]:w-5">{i as ReactNode}</span>{String(s)[0].toUpperCase()+String(s).slice(1)}</button>)}</nav>
    <InviteDialog open={inviteOpen} setOpen={setInviteOpen} busy={busy} onSubmit={async p=>{if(await action({action:"invite",projectId:project?.id,...p},"Invitation préparée"))setInviteOpen(false)}}/>
    <EventDialog open={eventOpen} setOpen={setEventOpen} projects={data.projects} members={data.allMembers} busy={busy} onSubmit={async p=>{if(await action({action:"addEvent",...p},"Intervention ajoutée"))setEventOpen(false)}}/>
    <ManageEventDialog event={manageEvent} setEvent={setManageEvent} members={data.allMembers} busy={busy} onSave={async(memberIds)=>{if(manageEvent&&await action({action:"updateEventMembers",projectId:manageEvent.project_id,eventId:manageEvent.id,memberIds},"Équipe modifiée"))setManageEvent(null)}} onDelete={async()=>{if(manageEvent&&await action({action:"deleteEvent",projectId:manageEvent.project_id,eventId:manageEvent.id},"Intervention supprimée"))setManageEvent(null)}}/>
    {project&&<DeleteProjectDialog open={deleteOpen} setOpen={setDeleteOpen} project={project} busy={busy} onConfirm={async()=>{if(await action({action:"deleteProject",projectId:project.id},"Chantier supprimé")){setDeleteOpen(false);setSection("chantiers")}}}/>} 
  </div>
}

function ProjectDetail({project,tab,setTab,data,query,setQuery,note,setNote,busy,filteredFiles,addNote,toggleNote,upload,onDelete}:{project:Project;tab:string;setTab:(v:string)=>void;data:Dashboard;query:string;setQuery:(v:string)=>void;note:string;setNote:(v:string)=>void;busy:boolean;filteredFiles:FileRow[];addNote:()=>void;toggleNote:(id:string)=>void;upload:(f:File)=>void;onDelete:()=>void}){
  const docs=filteredFiles.filter(f=>f.kind==="document"),photos=data.files.filter(f=>f.kind==="photo");
  return <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-4 border-b p-4 md:flex-row md:items-center md:justify-between md:px-6"><div><div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full" style={{background:project.color}}/><h2 className="text-lg font-extrabold">{project.name}</h2><span className="rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-700">En cours</span></div><p className="mt-1 text-sm text-slate-500">{project.address}{project.due_date?` · Livraison prévue le ${new Date(project.due_date).toLocaleDateString("fr-FR")}`:""}</p></div><div className="flex gap-2"><Button variant="outline" size="sm"><Users/> {data.members.length} membre{data.members.length>1?"s":""}</Button>{data.canAdminProject&&<Button variant="outline" size="sm" onClick={onDelete} className="border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700"><Trash2/> Supprimer</Button>}</div></div>
    <Tabs value={tab} onValueChange={setTab}><div className="overflow-x-auto border-b px-4 md:px-6"><TabsList className="h-12 bg-transparent"><TabsTrigger value="apercu">Aperçu</TabsTrigger><TabsTrigger value="documents">Documents {docs.length}</TabsTrigger><TabsTrigger value="photos">Photos {photos.length}</TabsTrigger><TabsTrigger value="modifications">Modifications {data.notes.filter(n=>!n.done).length}</TabsTrigger></TabsList></div>
      <TabsContent value="apercu" className="grid gap-5 p-4 lg:grid-cols-2 md:p-6"><div><h3 className="mb-3 font-extrabold">Avancement</h3><div className="rounded-xl bg-slate-50 p-4"><div className="mb-2 flex justify-between text-sm"><span>Progression générale</span><b>{project.progress} %</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-[#29756d]" style={{width:`${project.progress}%`}}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric value={String(data.files.length)} label="Fichiers"/><Metric value={String(data.notes.length)} label="Modifications"/><Metric value={String(data.members.length)} label="Membres"/></div></div></div><div><h3 className="mb-3 font-extrabold">Dernière activité</h3>{data.activities.length?data.activities.slice(0,3).map(a=><ActivityItem key={a.id} a={a}/>):<Empty text="Aucune activité pour le moment."/>}</div></TabsContent>
      <TabsContent value="documents" className="p-4 md:p-6"><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border px-3"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-10 w-full outline-none" placeholder="Rechercher un document"/></div><UploadButton accept=".pdf,.doc,.docx,.xls,.xlsx,.dwg,.dxf,image/*" busy={busy} label="Ajouter un fichier" onFile={upload}/></div>{docs.length?<div className="divide-y">{docs.map(f=><FileItem key={f.id} f={f}/>)}</div>:<Empty text="Aucun document. Ajoutez le premier plan du chantier."/>}</TabsContent>
      <TabsContent value="photos" className="p-4 md:p-6"><UploadButton accept="image/*" busy={busy} label="Appareil photo ou photothèque" large onFile={upload}/>{photos.length?<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{photos.map(f=><a key={f.id} href={`/api/files/${f.id}`} target="_blank" className="group relative aspect-[4/3] overflow-hidden rounded-xl bg-slate-200"><img src={`/api/files/${f.id}`} alt={f.name} className="h-full w-full object-cover"/><span className="absolute bottom-2 left-2 max-w-[85%] truncate rounded bg-white/90 px-2 py-1 text-xs font-bold">{f.name}</span></a>)}</div>:<Empty text="Aucune photo pour ce chantier."/>}</TabsContent>
      <TabsContent value="modifications" className="p-4 md:p-6"><div className="mb-5 flex flex-col gap-2 sm:flex-row"><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ajouter une modification ou une consigne…"/><Button disabled={busy||!note.trim()} onClick={addNote} className="self-end bg-[#165b54]">Ajouter</Button></div><div className="space-y-3">{data.notes.map(n=><div key={n.id} className={`rounded-xl border-l-4 p-4 ${n.done?"border-l-emerald-500 bg-emerald-50/60":"border-l-amber-400 bg-amber-50"}`}><div className="flex justify-between gap-3"><p className={n.done?"line-through opacity-65":"font-medium"}>{n.body}</p><button onClick={()=>toggleNote(n.id)}><Check className={n.done?"text-emerald-600":"text-slate-400"}/></button></div><div className="mt-2 text-xs text-slate-500">{n.author_name} · {fmtDate(n.created_at)} à {fmtTime(n.created_at)}</div></div>)}</div></TabsContent>
    </Tabs></section>
}

function NewProject({open,setOpen,busy,onSubmit}:{open:boolean;setOpen:(v:boolean)=>void;busy:boolean;onSubmit:(p:any)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl bg-[#165b54]"><Plus/> Nouveau chantier</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nouveau chantier</DialogTitle><DialogDescription>Créez le dossier, puis ajoutez les personnes autorisées.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({name:f.get("name"),address:f.get("address"),dueDate:f.get("dueDate")})}}><Input name="name" required placeholder="Nom du chantier"/><Input name="address" placeholder="Adresse"/><Input name="dueDate" type="date"/><Button disabled={busy} className="w-full bg-[#165b54]">Créer le chantier</Button></form></DialogContent></Dialog>}
function InviteDialog({open,setOpen,busy,onSubmit}:{open:boolean;setOpen:(v:boolean)=>void;busy:boolean;onSubmit:(p:any)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Inviter sur ce chantier</DialogTitle><DialogDescription>Cette personne ne verra que les chantiers auxquels elle est ajoutée.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({name:f.get("name"),email:f.get("email"),role:f.get("role")})}}><Input name="name" required placeholder="Prénom et nom"/><Input name="email" required type="email" placeholder="adresse@entreprise.fr"/><select name="role" className="h-10 w-full rounded-xl border bg-white px-3"><option value="member">Peut consulter et ajouter</option><option value="admin">Peut aussi gérer le chantier</option></select><Button disabled={busy} className="w-full bg-[#165b54]">Préparer l’invitation</Button></form></DialogContent></Dialog>}
function DeleteProjectDialog({open,setOpen,project,busy,onConfirm}:{open:boolean;setOpen:(v:boolean)=>void;project:Project;busy:boolean;onConfirm:()=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Supprimer « {project.name} » ?</DialogTitle><DialogDescription>Cette action supprimera définitivement le chantier, ses interventions, ses documents et ses photos. Elle est irréversible.</DialogDescription></DialogHeader><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Annuler</Button><Button disabled={busy} onClick={onConfirm} className="bg-red-600 text-white hover:bg-red-700">{busy?<Loader2 className="animate-spin"/>:<Trash2/>} Supprimer définitivement</Button></div></DialogContent></Dialog>}
function EventDialog({open,setOpen,projects,members,busy,onSubmit}:{open:boolean;setOpen:(v:boolean)=>void;projects:Project[];members:ProjectMember[];busy:boolean;onSubmit:(p:any)=>void}){const [projectId,setProjectId]=useState(projects[0]?.id??"");useEffect(()=>{if(open)setProjectId(projects[0]?.id??"")},[open,projects]);const available=members.filter(m=>m.project_id===projectId);return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Ajouter une intervention</DialogTitle><DialogDescription>Choisissez directement les personnes concernées.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({projectId:f.get("projectId"),title:f.get("title"),startsAt:new Date(String(f.get("startsAt"))).toISOString(),endsAt:new Date(String(f.get("endsAt"))).toISOString(),memberIds:f.getAll("memberIds").map(String)})}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} className="h-10 w-full rounded-xl border bg-white px-3">{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Input name="title" required placeholder="Intervention"/><Input name="startsAt" required type="datetime-local"/><Input name="endsAt" required type="datetime-local"/><MemberChecklist members={available}/><Button disabled={busy} className="w-full bg-[#165b54]">Ajouter à l’agenda</Button></form></DialogContent></Dialog>}
function ManageEventDialog({event,setEvent,members,busy,onSave,onDelete}:{event:EventRow|null;setEvent:(event:EventRow|null)=>void;members:ProjectMember[];busy:boolean;onSave:(memberIds:string[])=>void;onDelete:()=>void}){const [selected,setSelected]=useState<string[]>([]);useEffect(()=>{setSelected(event?.assigned_members.map(member=>member.id)??[])},[event]);if(!event)return null;const available=members.filter(member=>member.project_id===event.project_id);return <Dialog open={Boolean(event)} onOpenChange={open=>{if(!open)setEvent(null)}}><DialogContent><DialogHeader><DialogTitle>{event.title}</DialogTitle><DialogDescription>{event.project_name} · Choisissez les personnes concernées ou supprimez l’intervention.</DialogDescription></DialogHeader><MemberChecklist members={available} selected={selected} onChange={setSelected}/><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-between"><Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm(`Supprimer l’intervention « ${event.title} » ?`))onDelete()}} className="border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700"><Trash2/> Supprimer l’intervention</Button><Button disabled={busy} onClick={()=>onSave(selected)} className="bg-[#165b54]">Enregistrer l’équipe</Button></div></DialogContent></Dialog>}
function MemberChecklist({members,selected,onChange}:{members:ProjectMember[];selected?:string[];onChange?:(ids:string[])=>void}){return <fieldset className="rounded-xl border p-3"><legend className="px-1 text-sm font-bold">Membres concernés</legend>{members.length?<div className="grid max-h-48 gap-2 overflow-y-auto">{members.map(member=>{const checked=selected?selected.includes(member.id):false;return <label key={member.id} className="flex cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-slate-50"><input type="checkbox" name={selected?undefined:"memberIds"} value={member.id} checked={selected?checked:undefined} onChange={selected&&onChange?()=>onChange(checked?selected.filter(id=>id!==member.id):[...selected,member.id]):undefined} className="h-5 w-5 accent-[#165b54]"/><span className="font-semibold">{member.display_name}</span><span className="ml-auto text-xs text-slate-500">{member.role==="admin"?"Admin":"Membre"}</span></label>})}</div>:<p className="py-2 text-sm text-slate-500">Aucun membre pour ce chantier.</p>}</fieldset>}

function ProjectGrid({projects,onSelect}:{projects:Project[];onSelect:(id:string)=>void}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{projects.map(p=><button key={p.id} onClick={()=>onSelect(p.id)} className="rounded-2xl border bg-white p-5 text-left shadow-sm hover:-translate-y-0.5"><div className="mb-4 flex items-center justify-between"><span className="h-3 w-3 rounded-full" style={{background:p.color}}/><ChevronRight/></div><h2 className="text-lg font-extrabold">{p.name}</h2><p className="mt-1 text-sm text-slate-500">{p.address}</p><div className="mt-5 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#29756d]" style={{width:`${p.progress}%`}}/></div><div className="mt-2 text-right text-xs font-bold">{p.progress} %</div></button>)}</div>}
function TeamView({members,currentEmail,canAdmin,busy,onInvite,onRoleChange,onDelete,onPhoto}:{members:CompanyMember[];currentEmail:string;canAdmin:boolean;busy:boolean;onInvite:()=>void;onRoleChange:(memberId:string,role:string)=>void;onDelete:(memberId:string)=>void;onPhoto:(memberId:string,file:File)=>void}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-extrabold">Équipe de l’entreprise</h2><p className="mt-1 text-sm text-slate-500">{members.length} personne{members.length>1?"s":""} · Les administrateurs gèrent les autorisations, les photos et les départs.</p></div>{canAdmin&&<Button onClick={onInvite} className="bg-[#165b54]"><Plus/>Ajouter un membre</Button>}</div><div className="divide-y">{members.map(m=>{const ownAccount=m.email?.toLowerCase()===currentEmail.toLowerCase();return <div key={m.id} className="flex flex-wrap items-center gap-3 py-4"><label className={`relative grid h-14 w-14 shrink-0 overflow-hidden rounded-full bg-[#e3f2ef] font-bold text-[#165b54] ${canAdmin&&!busy?"cursor-pointer":""}`} title={canAdmin?"Modifier la photo":""}>{m.has_avatar?<img src={`/api/team-photo/${encodeURIComponent(m.id)}?v=${encodeURIComponent(m.avatar_version||"")}`} alt={m.display_name} className="h-full w-full object-cover"/>:<span className="grid h-full w-full place-items-center">{initials(m.display_name)}</span>}{canAdmin&&<input type="file" accept="image/*" className="hidden" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)onPhoto(m.id,file);e.currentTarget.value=""}}/>}</label><div className="min-w-40 flex-1"><div className="font-bold">{m.display_name}</div><div className="text-sm text-slate-500">{m.email||"Membre de l’équipe"}</div><div className="mt-1 text-xs text-slate-400">{canAdmin?"Touchez la photo pour la modifier":""}</div></div>{canAdmin?<select aria-label={`Autorisations de ${m.display_name}`} disabled={busy||ownAccount} value={m.role} onChange={e=>onRoleChange(m.id,e.target.value)} className="h-9 rounded-xl border bg-white px-3 text-sm font-semibold"><option value="member">Membre</option><option value="admin">Administrateur</option></select>:<span className="text-sm font-semibold">{m.role==="admin"?"Administrateur":"Membre"}</span>}<span className={`rounded-full px-2 py-1 text-xs font-bold ${m.status==="invited"?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700"}`}>{m.status==="invited"?"En attente":"Actif"}</span>{canAdmin&&!ownAccount&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>{if(window.confirm(`Supprimer ${m.display_name} de l’entreprise ? Cette personne sera retirée de tous les chantiers.`))onDelete(m.id)}} className="border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700"><Trash2/>Supprimer</Button>}{ownAccount&&<span className="text-xs font-semibold text-slate-400">Votre compte</span>}</div>})}</div></section>}
function AgendaView({events,onAdd,onManage}:{events:EventRow[];onAdd:()=>void;onManage:(event:EventRow)=>void}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-extrabold">Toutes les interventions</h2><Button onClick={onAdd} className="bg-[#165b54]"><Plus/>Ajouter</Button></div><WeekStrip/><div className="mt-5 space-y-3">{events.map(e=><EventItem key={e.id} e={e} onManage={()=>onManage(e)}/>)}</div></section>}
function TimeView({timer,timeText,onToggle}:{timer:Dashboard["timer"];timeText:string;onToggle:()=>void}){return <div className="mx-auto max-w-xl rounded-3xl bg-[#123f3b] p-8 text-center text-white shadow-lg"><Clock3 className="mx-auto mb-5 h-12 w-12 text-emerald-200"/><div className="text-sm text-emerald-100">{timer?"Pointage en cours":"Prêt à pointer"}</div><div className="my-5 text-5xl font-black tabular-nums">{timer?timeText:"00:00:00"}</div><Button onClick={onToggle} className="w-full bg-white text-[#123f3b] hover:bg-emerald-50">{timer?<><Pause/>Arrêter</>:<><Play/>Démarrer</>}</Button></div>}
function WeekStrip(){const d=new Date();return <div className="grid grid-cols-7 gap-1">{days.map((name,i)=><div key={name} className={`rounded-xl py-2 text-center ${i===((d.getDay()+6)%7)?"bg-[#165b54] text-white":""}`}><div className="text-xs opacity-70">{name}</div><div className="mt-1 font-extrabold">{new Date(d.getFullYear(),d.getMonth(),d.getDate()-((d.getDay()+6)%7)+i).getDate()}</div></div>)}</div>}
function EventItem({e,onManage}:{e:EventRow;onManage?:()=>void}){return <div className="flex gap-3"><div className="w-12 pt-3 text-sm font-bold text-slate-500">{fmtTime(e.starts_at)}</div><div className="flex-1 rounded-xl border-l-4 bg-slate-50 p-3" style={{borderLeftColor:e.color}}><div className="flex items-start justify-between gap-2"><div className="font-extrabold">{e.title}</div>{onManage&&<button onClick={onManage} className="rounded-lg px-2 py-1 text-xs font-bold text-[#165b54] hover:bg-emerald-50">Gérer</button>}</div><div className="text-sm text-slate-500">{e.project_name} · {e.address} · jusqu’à {fmtTime(e.ends_at)}</div><div className="mt-2 text-xs font-semibold text-slate-600">{e.assigned_members.length?e.assigned_members.map(member=>member.display_name).join(" · "):"Aucun membre assigné"}</div></div></div>}
function Nav({icon,label,active,badge,onClick}:{icon:ReactNode;label:string;active?:boolean;badge?:string;onClick:()=>void}){return <button onClick={onClick} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold ${active?"bg-[#e3f2ef] text-[#165b54]":"text-slate-600 hover:bg-slate-100"}`}><span className="[&>svg]:h-5 [&>svg]:w-5">{icon}</span><span className="flex-1 text-left">{label}</span>{badge&&<span className="rounded-full bg-slate-200 px-2 text-xs">{badge}</span>}</button>}
function Person({m}:{m:Member}){return <div className="mb-3 flex items-center gap-3 last:mb-0"><div className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-xs font-bold">{initials(m.display_name)}</div><div className="min-w-0 flex-1"><div className="font-bold">{m.display_name}</div><div className="truncate text-xs text-slate-500">{m.role==="admin"?"Administrateur":"Membre"}</div></div><span className="text-xs font-semibold text-[#29756d]">{m.status==="invited"?"Invité":"Actif"}</span></div>}
function Metric({value,label}:{value:string;label:string}){return <div><div className="text-lg font-black">{value}</div><div className="text-xs text-slate-500">{label}</div></div>}
function ActivityItem({a}:{a:Activity}){return <div className="mb-2 flex items-center gap-3 rounded-xl border p-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-[#29756d]"><FileText size={17}/></div><div><div className="font-bold">{a.detail}</div><div className="text-xs text-slate-500">{a.actor_name} · {fmtDate(a.created_at)} à {fmtTime(a.created_at)}</div></div></div>}
function FileItem({f}:{f:FileRow}){return <a href={`/api/files/${f.id}`} target="_blank" className="flex items-center gap-3 py-3 hover:bg-slate-50"><div className="grid h-10 w-10 place-items-center rounded-lg bg-red-50 text-xs font-black text-red-600">{f.name.split(".").pop()?.slice(0,3).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="truncate font-bold">{f.name}</div><div className="text-sm text-slate-500">{f.uploaded_by_name} · {(f.size/1024/1024).toFixed(1)} Mo</div></div><Download size={18}/></a>}
function UploadButton({accept,capture,busy,label,large,onFile}:{accept:string;capture?:boolean;busy:boolean;label:string;large?:boolean;onFile:(f:File)=>void}){return <label className={`inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl font-bold ${large?"w-full border-2 border-dashed border-slate-300 p-7 text-slate-600":"bg-[#165b54] px-4 py-2 text-sm text-white"}`}>{busy?<Loader2 className="animate-spin"/>:large?<Camera/>:<Upload size={17}/>} {label}<input type="file" accept={accept} capture={capture?"environment":undefined} className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f);e.currentTarget.value=""}}/></label>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-7 text-center text-sm text-slate-500">{text}</div>}
function State({icon,title,action}:{icon:ReactNode;title:string;action?:()=>void}){return <div className="grid min-h-screen place-items-center bg-[#f3f5f7]"><div className="text-center"><div className="mx-auto mb-3 flex justify-center text-[#165b54]">{icon}</div><p className="font-bold">{title}</p>{action&&<Button onClick={action} className="mt-4">Réessayer</Button>}</div></div>}
